export const CHART_TRACKS_REQUEST = 'CHART_TRACKS_REQUEST';
export const CHART_TRACKS_SUCCESS = 'CHART_TRACKS_SUCCESS';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
